steps:
  - id: 'terraform-init'
    name: 'hashicorp/terraform:1.11.4'
    args: ['init']
    dir: 'terraform/environments/${_ENVIRONMENT}'

  - id: 'terraform-validate'
    name: 'hashicorp/terraform:1.11.4'
    args: ['validate']
    dir: 'terraform/environments/${_ENVIRONMENT}'
    waitFor: ['terraform-init']

  # Remove a specific resource
  - id: 'terraform-rm-one-state'
    name: 'hashicorp/terraform:1.11.4'
    # Ensure _RESOURCE_TARGET is a valid resource address from `terraform state list`
    args: ['state', 'rm', '${_RESOURCE_TARGET}'] 
    dir: 'terraform/environments/${_ENVIRONMENT}'
    waitFor: ['terraform-validate']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ENVIRONMENT: 'dev'
  # Example: Use the actual resource address from your state file
  _RESOURCE_TARGET: 'module.database.google_sql_database_instance.postgresql_instance'