
steps:
  - id: 'terraform-init'
    name: 'hashicorp/terraform:1.11.4'
    args: ['init']
    dir: 'terraform/environments/${_ENVIRONMENT}'

  - id: 'terraform-validate'
    name: 'hashicorp/terraform:1.11.4'
    args: ['validate']
    dir: 'terraform/environments/${_ENVIRONMENT}'
    waitFor: ['terraform-init']

  # Remove a specific resource
  - id: 'terraform-rm-one-state'
    name: 'hashicorp/terraform:1.11.4'
    args: ['state', 'rm', '${_RESOURCE_TARGET}']
    dir: 'terraform/environments/${_ENVIRONMENT}'
    waitFor: ['terraform-validate']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ENVIRONMENT: 'dev'
