steps:
  # Remove a specific resource from the Terraform state
  - id: 'terraform-destroy-target'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args:
      - 'destroy'
      - '-auto-approve'
      - '-target=${_RESOURCE_TARGET}'
    dir: 'terraform/environments/${_ENVIRONMENT}'

options:
  logging: CLOUD_LOGGING_ONLY

