
steps:
  # Remove a specific resource
  - id: 'terraform-destroy-target'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args:
      - 'destroy'
      - '-auto-approve'
      - '-target=${_RESOURCE_TARGET}'
     dir: 'terraform/environments/${_ENV}' 

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ENV: dev