steps:
  - id: 'terraform-init'
    name: 'hashicorp/terraform:1.11.4'
    args: ['init']
    dir: 'terraform/environments/dev'

  - id: 'terraform-validate'
    name: 'hashicorp/terraform:1.11.4'
    args: ['validate']
    dir: 'terraform/environments/dev'
    waitFor: ['terraform-init']

  # Show destruction plan (optional but recommended for safety)
  - id: 'terraform-plan-destroy'
    name: 'hashicorp/terraform:1.11.4'
    args: ['plan', '-destroy']
    env:
      - 'TF_VAR_project_id=${_PROJECT_ID}'
      - 'TF_VAR_region=${_REGION}'
      - 'TF_VAR_environment=${_ENVIRONMENT}'
      - 'TF_VAR_subnetwork_address=${_SUBNETWORK_ADDRESS}'
      - 'TF_VAR_business_database_name=${_BUSINESS_DATABASE_NAME}'
      - 'TF_VAR_business_database_user_name=${_BUSINESS_DATABASE_USER_NAME}'
      - 'TF_VAR_business_db_password_secret_name=${_BUSINESS_DB_PASSWORD_SECRET_NAME}'
      - 'TF_VAR_superset_database_name=${_SUPERSET_DATABASE_NAME}'
      - 'TF_VAR_superset_database_user_name=${_SUPERSET_DATABASE_USER_NAME}'
      - 'TF_VAR_superset_db_password_secret_name=${_SUPERSET_DB_PASSWORD_SECRET_NAME}'
      - 'TF_VAR_bigquery_owner_user=${_BIGQUERY_OWNER_USER}'
      - 'TF_VAR_bigquery_analyst_user=${_BIGQUERY_ANALYST_USER}'
      - 'TF_VAR_bigquery_contributor_user=${_BIGQUERY_CONTRIBUTOR_USER}'
      - 'TF_VAR_cloud_composer_admin_email=${_CLOUD_COMPOSER_ADMIN_EMAIL}'
      - 'TF_VAR_gke_master_ipv4_cidr_block=${_GKE_MASTER_IPV4_CIDR_BLOCK}'
      - 'TF_VAR_vpc_network_name=${_VPC_NETWORK_NAME}'
      - 'TF_VAR_state_file_bucket=${_STATE_FILE_BUCKET}'
      - 'TF_VAR_secret_version=${_SECRET_VERSION}'
      - 'TF_VAR_superset_admin_username=${_SUPERSET_ADMIN_USER}'
      - 'TF_VAR_superset_admin_password=${_SUPERSET_ADMIN_PASSWORD}'
      - 'TF_VAR_superset_admin_email=${_SUPERSET_ADMIN_EMAIL}'
    dir: 'terraform/environments/dev'
    waitFor: ['terraform-validate']

  # Destroy everything
  - id: 'terraform-destroy'
    name: 'hashicorp/terraform:1.11.4'
    args: ['destroy', '-auto-approve']
    env:
      - 'TF_VAR_project_id=${_PROJECT_ID}'
      - 'TF_VAR_region=${_REGION}'
      - 'TF_VAR_environment=${_ENVIRONMENT}'
      - 'TF_VAR_subnetwork_address=${_SUBNETWORK_ADDRESS}'
      - 'TF_VAR_business_database_name=${_BUSINESS_DATABASE_NAME}'
      - 'TF_VAR_business_database_user_name=${_BUSINESS_DATABASE_USER_NAME}'
      - 'TF_VAR_business_db_password_secret_name=${_BUSINESS_DB_PASSWORD_SECRET_NAME}'
      - 'TF_VAR_superset_database_name=${_SUPERSET_DATABASE_NAME}'
      - 'TF_VAR_superset_database_user_name=${_SUPERSET_DATABASE_USER_NAME}'
      - 'TF_VAR_superset_db_password_secret_name=${_SUPERSET_DB_PASSWORD_SECRET_NAME}'
      - 'TF_VAR_bigquery_owner_user=${_BIGQUERY_OWNER_USER}'
      - 'TF_VAR_bigquery_analyst_user=${_BIGQUERY_ANALYST_USER}'
      - 'TF_VAR_bigquery_contributor_user=${_BIGQUERY_CONTRIBUTOR_USER}'
      - 'TF_VAR_cloud_composer_admin_email=${_CLOUD_COMPOSER_ADMIN_EMAIL}'
      - 'TF_VAR_gke_master_ipv4_cidr_block=${_GKE_MASTER_IPV4_CIDR_BLOCK}'
      - 'TF_VAR_vpc_network_name=${_VPC_NETWORK_NAME}'
      - 'TF_VAR_state_file_bucket=${_STATE_FILE_BUCKET}'
      - 'TF_VAR_secret_version=${_SECRET_VERSION}'
      - 'TF_VAR_superset_admin_username=${_SUPERSET_ADMIN_USER}'
      - 'TF_VAR_superset_admin_password=${_SUPERSET_ADMIN_PASSWORD}'
      - 'TF_VAR_superset_admin_email=${_SUPERSET_ADMIN_EMAIL}'
    dir: 'terraform/environments/dev'
    waitFor: ['terraform-plan-destroy']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: 'dbt-project-dvd-rent'
  _REGION: 'us-central1'
  _ENVIRONMENT: 'dev'
  _SUBNETWORK_ADDRESS: '10.0.0.0/24'
  _BUSINESS_DATABASE_NAME: 'dvd_rental_db'
  _BUSINESS_DATABASE_USER_NAME: 'datastream_user'
  _BUSINESS_DB_PASSWORD_SECRET_NAME: 'your-db-password-secret'
  _SUPERSET_DATABASE_NAME: 'superset'
  _SUPERSET_DATABASE_USER_NAME: 'superset'
  _SUPERSET_DB_PASSWORD_SECRET_NAME: 'your-db-password-secret'
  _BIGQUERY_OWNER_USER: 'user-owner@example.com'
  _BIGQUERY_ANALYST_USER: 'user-analyst@example.com'
  _BIGQUERY_CONTRIBUTOR_USER: 'user-contributor@example.com'
  _VPC_NETWORK_NAME: 'datastream-vpc'
  _GKE_MASTER_IPV4_CIDR_BLOCK: '172.16.0.0/28'
  _CLOUD_COMPOSER_ADMIN_EMAIL: 'user-owner@example.com'
  _PRIVATE_POOL_NAME: 'private-pool' 
  _STATE_FILE_BUCKET: 'state-files-dev'
  _SECRET_VERSION: '1'
  _SUPERSET_ADMIN_USER: 'admin'
  _SUPERSET_ADMIN_PASSWORD: 'admin'
  _SUPERSET_ADMIN_EMAIL: 'admin@example.com'
