steps:
  - id: 'terraform-init'
    name: 'hashicorp/terraform:1.11.4'
    args: ['init']
    dir: 'terraform/environments/dev'

  - id: 'terraform-validate'
    name: 'hashicorp/terraform:1.11.4'
    args: ['validate']
    dir: 'terraform/environments/dev'
    waitFor: ['terraform-init']

  - id: 'terraform-import'
    name: 'hashicorp/terraform:1.11.4' 
    args: ['import', 'google_storage_bucket.state-files-dev', 'state-files-dev']
    dir: 'terraform/environments/dev'
    waitFor: ['terraform-validate'] 

options:
  logging: CLOUD_LOGGING_ONLY