steps:
  - id: 'terraform-init'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y \
          unzip \
          netcat-traditional \
          postgresql-client # Assurez-vous que psql est là pour le local-exec
        
        curl -LO https://releases.hashicorp.com/terraform/1.11.4/terraform_1.11.4_linux_amd64.zip
        unzip terraform_1.11.4_linux_amd64.zip
        mv terraform /usr/local/bin/
        rm terraform_1.11.4_linux_amd64.zip
        
        terraform init
    dir: 'terraform/environments/dev'

  - id: 'terraform-validate'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y \
          unzip \
          netcat-traditional \
          postgresql-client
        
        curl -LO https://releases.hashicorp.com/terraform/1.11.4/terraform_1.11.4_linux_amd64.zip
        unzip terraform_1.11.4_linux_amd64.zip
        mv terraform /usr/local/bin/
        rm terraform_1.11.4_linux_amd64.zip
        
        terraform validate
    dir: 'terraform/environments/dev'
    waitFor: ['terraform-init']

  - id: 'terraform-plan'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y \
          unzip \
          netcat-traditional \
          postgresql-client
        
        curl -LO https://releases.hashicorp.com/terraform/1.11.4/terraform_1.11.4_linux_amd64.zip
        unzip terraform_1.11.4_linux_amd64.zip
        mv terraform /usr/local/bin/
        rm terraform_1.11.4_linux_amd64.zip
        
        terraform plan -out=tfplan
    env:
      - 'TF_VAR_project_id=${_PROJECT_ID}'
      - 'TF_VAR_region=${_REGION}'
      - 'TF_VAR_environment=${_ENVIRONMENT}'
      - 'TF_VAR_subnetwork_address=${_SUBNETWORK_ADDRESS}'
      - 'TF_VAR_database_name=${_DATABASE_NAME}'
      - 'TF_VAR_database_user_name=${_DATABASE_USER_NAME}'
      - 'TF_VAR_db_password_secret_name=${_DB_PASSWORD_SECRET_NAME}'
      - 'TF_VAR_bigquery_owner_user=${_BIGQUERY_OWNER_USER}'
      - 'TF_VAR_bigquery_analyst_user=${_BIGQUERY_ANALYST_USER}'
      - 'TF_VAR_bigquery_contributor_user=${_BIGQUERY_CONTRIBUTOR_USER}'
      - 'TF_VAR_vpc_network_name=${_VPC_NETWORK_NAME}'
    dir: 'terraform/environments/dev'
    waitFor: ['terraform-validate']

  - id: 'terraform-list'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y \
          unzip \
          netcat-traditional \
          postgresql-client
        
        curl -LO https://releases.hashicorp.com/terraform/1.11.4/terraform_1.11.4_linux_amd64.zip
        unzip terraform_1.11.4_linux_amd64.zip
        mv terraform /usr/local/bin/
        rm terraform_1.11.4_linux_amd64.zip
        
        terraform destroy -auto-approve --target=${_RESOURCE_TARGET} tfplan
    env:
      - 'TF_VAR_project_id=${_PROJECT_ID}'
      - 'TF_VAR_region=${_REGION}'
      - 'TF_VAR_environment=${_ENVIRONMENT}'
      - 'TF_VAR_subnetwork_address=${_SUBNETWORK_ADDRESS}'
      - 'TF_VAR_database_name=${_DATABASE_NAME}'
      - 'TF_VAR_database_user_name=${_DATABASE_USER_NAME}'
      - 'TF_VAR_db_password_secret_name=${_DB_PASSWORD_SECRET_NAME}'
      - 'TF_VAR_bigquery_owner_user=${_BIGQUERY_OWNER_USER}'
      - 'TF_VAR_bigquery_analyst_user=${_BIGQUERY_ANALYST_USER}'
      - 'TF_VAR_bigquery_contributor_user=${_BIGQUERY_CONTRIBUTOR_USER}'
      - 'TF_VAR_vpc_network_name=${_VPC_NETWORK_NAME}'
    dir: 'terraform/environments/dev'
    waitFor: ['terraform-plan']

options:
  logging: CLOUD_LOGGING_ONLY
  workerPool: 'projects/${_PROJECT_ID}/locations/${_REGION}/workerPools/${_PRIVATE_POOL_NAME}'

substitutions:
  _PROJECT_ID: 'dbt-project-dvd-rent'
  _REGION: 'europe-west9'
  _ENVIRONMENT: 'dev'
  _SUBNETWORK_ADDRESS: '10.0.0.0/24'
  _DATABASE_NAME: 'dvd_rental_db'
  _DATABASE_USER_NAME: 'datastream_user'
  _DB_PASSWORD_SECRET_NAME: 'your-db-password-secret'
  _BIGQUERY_OWNER_USER: 'user-owner@example.com'
  _BIGQUERY_ANALYST_USER: 'user-analyst@example.com'
  _BIGQUERY_CONTRIBUTOR_USER: 'user-contributor@example.com'
  _VPC_NETWORK_NAME: 'datastream-vpc'
  _PRIVATE_POOL_NAME: 'private-pool' 