extraVolumes:
  - name: requirements
    configMap:
      name: superset-requirements

extraVolumeMounts:
  - name: requirements
    mountPath: /app/requirements
    readOnly: true

bootstrapScript: |
  #!/bin/bash
  
  # Install system-level dependencies
  apt-get update && apt-get install -y \
    python3-dev \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config

  # Install required Python packages
  uv pip install \
    authlib \
    psycopg2-binary \
    google-cloud-bigquery \

  # Create bootstrap file if it doesn't exist
  if [ ! -f ~/bootstrap ]; then
    echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap
  fi

# Configuration PostgreSQL
postgresql:
  enabled: true
  auth:
    database: superset
    username: superset

# Configuration Redis
redis:
  enabled: true

# Variables d'environnement supplémentaires
extraEnv:
  SUPERSET_LOAD_EXAMPLES: "no"


#service:
#  type: LoadBalancer
#  port: 8088
#  targetPort: 8088
#  annotations: {}