extraVolumes:
  - name: requirements
    configMap:
      name: superset-requirements

extraVolumeMounts:
  - name: requirements
    mountPath: /app/requirements
    readOnly: true

bootstrapScript: |
  #!/bin/bash
  
  # Install system-level dependencies
  apt-get update && apt-get install -y \
    python3-dev \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config

  # Install required Python packages
  uv pip install \
    authlib \
    psycopg2-binary \
    google-cloud-bigquery \

  # Create bootstrap file if it doesn't exist
  if [ ! -f ~/bootstrap ]; then
    echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap
  fi

# Configuration PostgreSQL
postgresql:
  enabled: true
  auth:
    database: superset
    username: superset

# Configuration Redis
redis:
  enabled: true

extraContainers:
  - name: cloudsql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
    command: 
      - "/cloud-sql-proxy"
    args:
      - "--port=5432"
      - "--address=0.0.0.0"
      - "$(CLOUD_SQL_INSTANCE_CONNECTION_NAME)"
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532

extraEnv:
  - CLOUD_SQL_INSTANCE_CONNECTION_NAME: "{{ .Values.connectionName }}"
  - SUPERSET_LOAD_EXAMPLES: "no"
