extraVolumes:
  - name: requirements
    configMap:
      name: superset-requirements

extraVolumeMounts:
  - name: requirements
    mountPath: /app/requirements
    readOnly: true

init:
  # This section overrides the default initContainers from the chart.
  initContainers:
    # A custom init container to run the Cloud SQL proxy and wait for the database connection.
    - name: wait-for-cloudsql-and-db
      image: alpine/curl:3.14
      command:
        - sh
        - -c
        - |
          # The Cloud SQL Proxy must run as a long-running process
          # Here we launch it as a background job within the init container.
          /cloud-sql-proxy --port=5432 "$(CLOUD_SQL_INSTANCE_CONNECTION_NAME)" &

          echo "Waiting for Cloud SQL Proxy to be up on localhost:5432..."
          while ! nc -z -w 1 localhost 5432; do
            sleep 1
          done
          echo "Cloud SQL Proxy is up. Now waiting for PostgreSQL database..."
          while ! nc -z -w 1 127.0.0.1 5432; do
            sleep 1
          done
          echo "Database is ready. Exiting init container."
      env:
        - name: CLOUD_SQL_INSTANCE_CONNECTION_NAME
          value: "{{ .Values.connectionName }}"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532

bootstrapScript: |
  #!/bin/bash
  
  # Install system-level dependencies
  apt-get update && apt-get install -y \
    python3-dev \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config

  # Install required Python packages
  uv pip install \
    authlib \
    psycopg2-binary \
    google-cloud-bigquery \

  # Create bootstrap file if it doesn't exist
  if [ ! -f ~/bootstrap ]; then
    echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap
  fi

# Configuration PostgreSQL
postgresql:
  enabled: false
  auth:
    database: superset
    username: superset

# Configuration Redis
redis:
  enabled: true

extraContainers: []

extraEnv:
  - CLOUD_SQL_INSTANCE_CONNECTION_NAME: "{{ .Values.connectionName }}"
  - SUPERSET_LOAD_EXAMPLES: "no"
